### ISSUE TITLE
I appreciate you creating such a wonderful piece of work, but I have a question I'd like to share with you。

### ISSUE THREAD

**Issue by 1977878681** [Bluemoondragon07/Obsidian-Serenity#10]
Thank you so much for creating such a wonderful work. Thank you. I have a problem that I need to feedback to you, that is, when the mouse moves near this area, it will appear a residual shadow like the Flash, but I cannot control its appearance, I hope you can solve it. Thank you again, I am a loyal user of your work.
![1](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/95575638/e63a838e-57e7-414b-8a7a-2e9d08a1e9f3)
![2](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/95575638/8845d3c2-08a1-4e24-8caa-52a926093eae)

**Comment by Bluemoondragon07** [comment]
I'm glad you enjoy my theme! I am not sure exactly what causes that effect. I know from issue #3 that on Mac computers the left sidebar has some appearance issues. If you're using a Mac, if you download the Style Settings plugin and go to `Style Settings > Serenity > Focus Mode Settings > Hidden Elements` you can turn off **Hide Sidebar Ribbon**, and it might fix the problem. 

Changing your window frame style in `Settings > Appearance` might also help. Let me know if the problem still persists.

**Comment by 1977878681** [comment]
Thanks for your answer, my friend. It can be solved, but this operation loses the function of automatic shrinkage. I like your design idea very much, just like the ease of retraction in Kung Fu. Anyway thank you for your prompt answer.
"Niubility"

**Comment by 1977878681** [comment]
Sorry friend, I can't understand you because it's machine translation, this flicker still exists, but it doesn't exist on mac, it's only a problem on Windows. English is not my native language, I'm sorry.

**Comment by 1977878681** [comment]
It's cool to be able to chat with big guys.

**Comment by alephpiece** [comment]
Is this behaviour the same as reported in #21?

**Comment by 1977878681** [comment]
Perfect piece of work, sorry for the fact that I rarely look at this site since I'm not a programmer. Your work is awesome. I would like to thank you and have a nice life.

**Comment by Bluemoondragon07** [comment]
Thank you; please have a nice life also!
