### ISSUE TITLE
Bug with the plugin Influx

### ISSUE THREAD

**Issue by Kullenej** [Bluemoondragon07/Obsidian-Serenity#12]
Thank you for a wonderful theme! Unfortunately, it makes the linked mentions section created by the plugin Influx unusable. 

Here is how it should look like (with another theme): 
<img width="895" alt="CleanShot 2023-05-24 at 15 25 59@2x" src="https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/86346980/bc2b40d5-0cf9-4c6f-b85d-96f87936c3ff">

Here is how it looks with Serenity: 
<img width="995" alt="CleanShot 2023-05-24 at 15 26 37@2x" src="https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/86346980/f87b9e01-70de-498e-a093-8fdad784cf83">

**Comment by Bluemoondragon07** [comment]
Hi! Thanks for pointing this issue out. After the latest update, the appearance of embedded backlinks can be controlled with Style Settings. As long as the link-like styling is turned off, the Influx plugin should now appear as expected.
