### ISSUE TITLE
Large gap between inline header and paragraph

### ISSUE THREAD

**Issue by eugeniashuvalova** [Bluemoondragon07/Obsidian-Serenity#18]
Hi! I'm in love with your amazing plugin, but there's an issue which I can't solve with style settings plugin. Or maybe I can't understand where I should look for that specific setting. I will be grateful for your help!

![IMG_7567](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/124776948/4f6e8a33-86bc-4987-a368-e4b9f01cd589)

Only in source mode I haven't this problem.

![IMG_7568](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/124776948/07dda170-0e3d-4d94-bd48-dcb5980bdd2d)
![IMG_7570](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/124776948/1b4b7df0-3c17-4bf5-9e57-0648ea8201a4)

**Comment by eugeniashuvalova** [comment]
Only in source mode I haven't this problem.

![IMG_7568](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/124776948/b3469bf6-114d-4786-ba1d-d2cbe0752e02)
![IMG_7570](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/124776948/e3c87963-4dd9-41d7-aa9e-3edfe2ab7473)

**Comment by Bluemoondragon07** [comment]
Should be fixed now after updating! The problem was caused by some styling designed to add some room for the properties between the title and the body text. Now, if you're hiding the properties via Obsidian's settings, it should display correctly.

**Comment by eugeniashuvalova** [comment]
Thank you!!
