### ISSUE TITLE
[FR] Option to disable autohide UI elements

### ISSUE THREAD

**Issue by danieltomasz** [Bluemoondragon07/Obsidian-Serenity#2]
Theme is great!

This my person preference, having clean interface is great but the "visual movement" when moving mouse to show UI elements distracts me as well, I would like to be able to disable autohiding of UI elements, so all of them are shown.

**Comment by Bluemoondragon07** [comment]
Glad you're enjoying the theme. I myself actually prefer to have the titlebar and tabs visible, but I decided for the early version to have these automatically hidden. I'll definitely add more specific control over these things at some point, though!

**Comment by danieltomasz** [comment]
yes, thank you! The theme just debuted, I  agree with you philosophy and understand  that there is not easy to add all possible features at once :)

**Comment by Bluemoondragon07** [comment]
I've added these options in the latest update! Enjoy.

**Comment by danieltomasz** [comment]
thanks it is really useful!
