### ISSUE TITLE
tab bar not working when the Make.md plugin is activated

### ISSUE THREAD

**Issue by erfanbashar1q** [Bluemoondragon07/Obsidian-Serenity#4]
Hi

when the Make.md plugin is activated, the tab bar is not coverable anymore, what I mean is when the tab bar focus mode is On, by activating the Make.md by hovering over it, it will not be shown anymore.

**Comment by erfanbashar1q** [comment]
also, in the space panel of the Make.md the files are not shown in a proper way, they are like this:
<img width="691" alt="Screenshot 2023-04-17 at 17 10 03" src="https://user-images.githubusercontent.com/116307599/232528718-43a4f015-a31b-4e05-b0b8-c3e51bf92a96.png">

**Comment by Bluemoondragon07** [comment]
Thanks for pointing this out, @erfanbashar1q . I'll look into fixing this 👍

**Comment by Bluemoondragon07** [comment]
Please update to the latest version; it fixes the file appearance.

I wasn't able to reproduce an instance of the tab bar not appearing on hover with MAKE.md, so I assume I fixed it somewhere when I was modifying the tabs, but let me know if it's still occuring.

Enjoy the update.
