### ISSUE TITLE
Hidden Elements

### ISSUE THREAD

**Issue by jdjshhc** [Bluemoondragon07/Obsidian-Serenity#6]
Hello, I would like to make a suggestion
At present, the hidden elements are folded and hidden, and then triggered to expand and display. Folding and unfolding is active, causing the interface to shake. (A)
can I
1. The display after folding is suspended and will not affect the interface layout (B)
2. Element hiding is not a folding method (excluding the second column function keys), it is purely hidden and does not affect the layout (C)
![微信图片_20230429144201](https://user-images.githubusercontent.com/106785928/235288043-42210b0d-66a7-4654-ab6a-83764a8ecc78.png)

**Comment by Bluemoondragon07** [comment]
I see what you mean. In the future, I'll add a Style Settings option that disables the folding transitions and instead will just change the opacity to look smoother. Thanks for the suggestion!
