### ISSUE TITLE
Work with iterative rainbow folder

### ISSUE THREAD

**Issue by hsin-pingwu** [Bluemoondragon07/Obsidian-Serenity#8]
Hi, I've been using this theme since its first release and I love it! Thanks for your great work!
And I always have the Iterative Rainbow Folder Title CSS snippet enabled (from the forum with some tweaks: https://forum.obsidian.md/t/iterative-rainbow-folder-colors-css/21066).
It worked nicely until the recent update of Obsidian to v1.2 (currently I'm using 1.2.7). 
The rainbow colors in the file explorer no longer show up.
Could you please take a look and perhaps make the theme work with this css snippet? Or let me know how to fix it?
By the way I also use and like your Chime theme, beautiful and working fine with this css snippet : )
Thanks a lot!

**Comment by Bluemoondragon07** [comment]
Hi, I'm glad you like my themes. I will definitely look into this. I think it might have something to do with the last update to Serenity, where I accidentally overrode some folder styles with css intended for backlinks. I technically have that fixed already, I just need to put it on Github. 

Still, I'll make sure the theme works with the snippet 👍🏽 .  And also, put the fix on Github.

Thanks for letting me know about this!

**Comment by hsin-pingwu** [comment]
Thanks a lot for fixing it!
