### ISSUE TITLE
Dataview Table Format Symmetry

### ISSUE THREAD

**Issue by kumar7vaibhav** [Bluemoondragon07/Obsidian-Serenity#9]
Thank you for this theme. I really loved it. 

After the recent update, the dataview TABLE columns are not properly centered and do not auto rezise the TABLE when added to right/left pane. 
 
 Editor
![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/75883783/3b7c9757-977d-4c12-836d-713697565552)

Right Pane - Clips the second column completely.
![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/75883783/0bae5476-906b-43b3-8830-460abe9acc43)

Comparing with Chime
![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/75883783/c957e63b-5386-4b8d-94e8-61848718df97)
![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/75883783/10d7e2a4-ceaa-47c1-b416-d5fc13a8d6e5)

**Comment by Bluemoondragon07** [comment]
Hi! I fixed the appearance issues in the latest update. Enjoy!
